let bill = 275;
let tip = (bill >= 50 && bill <= 300) ? ((15 / 100) * bill) : ((1 / 5) * bill);
console.log(tip);
let final = (bill + tip);
console.log(final);
bill = 40;
tip = (bill >= 50 && bill <= 300) ? ((15 / 100) * bill) : ((1 / 5) * bill);
console.log(tip);
final = (bill + tip);
console.log(final);
bill = 430;
tip = (bill >= 50 && bill <= 300) ? ((15 / 100) * bill) : ((1 / 5) * bill);
console.log(tip);
final = (bill + tip);
console.log(final);